#!/usr/bin/env sh
/home/username/wellingtonBusStuff/service_locations.py -s 1 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 110 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 111 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 112 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 113 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 114 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 115 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 12 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 120 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 121 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 12e -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 13 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 130 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 14 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 145 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 150 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 154 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 160 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 17 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 170 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 17e -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 18 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 18e -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 19 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 19e -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 2 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 20 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 200 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 201 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 202 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 203 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 204 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 206 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 21 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 210 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 22 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 220 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 226 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 23 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 230 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 236 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 23e -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 24 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 25 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 250 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 251 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 26 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 260 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 261 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 262 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 264 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 28 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 280 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 281 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 29 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 290 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 291 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 29e -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 3 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 300 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 30x -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 31x -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 32x -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 33 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 34 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 35 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 36 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 36a -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 37 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 3a -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 52 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 56 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 57 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 58 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 60 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 60e -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 7 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 80 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 81 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 83 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 84 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 85x -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 90 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 91 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 92 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s 93 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s N1 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s N2 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s N22 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s N3 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s N4 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s N5 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s N6 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s N66 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s N8 -i 15 -r 4 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_locations.py -s N88 -i 15 -r 4 --dbtype mariadb &
