#!/usr/bin/env sh
/home/username/wellingtonBusStuff/service_location.py -s 1 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 110 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 111 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 112 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 113 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 114 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 115 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 12 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 120 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 121 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 12e -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 13 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 130 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 14 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 145 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 150 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 154 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 160 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 17 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 170 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 17e -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 18 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 18e -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 19 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 19e -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 2 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 20 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 200 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 201 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 202 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 203 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 204 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 206 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 21 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 210 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 22 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 220 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 226 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 23 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 230 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 236 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 23e -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 24 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 25 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 250 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 251 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 26 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 260 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 261 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 262 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 264 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 28 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 280 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 281 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 29 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 290 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 291 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 29e -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 3 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 300 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 30x -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 31x -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 32x -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 33 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 34 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 35 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 36 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 36a -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 37 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 3a -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 52 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 56 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 57 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 58 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 60 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 60e -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 7 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 80 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 81 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 83 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 84 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 85x -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 90 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 91 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 92 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s 93 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s N1 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s N2 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s N22 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s N3 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s N4 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s N5 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s N6 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s N66 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s N8 -r 1 --dbtype mariadb &
/home/username/wellingtonBusStuff/service_location.py -s N88 -r 1 --dbtype mariadb &
